version: '3.1'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - es-nht:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash-oss:7.12.0-amd64
    ports:
      - "5044:5044"
    volumes:
      # - ./logstash/conf-wo-filebeat.d:/usr/share/logstash/pipeline/:ro
      - ./:/usr/share/logstash/custom-config
    depends_on:
      - elasticsearch
    networks:
      - elastic
    environment:
      - XPACK_MONITORING_ENABLED=false
    entrypoint: ["/bin/bash", "-c"]

    # sleep 3000 is for debugging -- remove it while running docker-compose
    command: ["sleep 3000 && ./bin/logstash -f custom-config/logstash/conf-wo-filebeat.d  --log.level debug | tee -a custom-config/logstash-logs.txt"]

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic

  # filebeat:
  #   container_name: filebeat
  #   image: 
  #   ports:
  #   depends_on:
  #     - elasticsearch
  #     - logstash
  #     - kibana
  #   entrypoint: ["/bin/sh","-c"]
  #   command:
  #   - |
  #       echo a
  #       echo b
  #       echo c
  #   networks:
  #     - filebeat

volumes:
  es-nht:
    driver: local

networks:
  elastic:
    driver: bridge
  filebeat:
    driver: bridge
